name: glukutux
description: UI design library implementation of Eva Design System
version: 0.1.0
author: Haqqi <haqqi@glovory.com>
homepage: http://glovory.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
