name: glova
description: Flutter UI component based on Eva Design System by Glovory
version: 0.1.0
homepage: https://glovory.com
repository: https://github.com/glovory/glova
issue_tracker: https://github.com/glovory/glova/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  eva_color: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
